---
title: "Education"
page-layout: article
listing:
  id: education-posts
  contents: listings/education.yml
  type: default
  sort: "date desc"
  categories: true
  sort-ui: false
  filter-ui: false
  feed: true
  image-height: "180px"
---

::: {.section-intro}

The group is involved in teaching and training at the University of Zurich (UZH) and beyond.

Education work includes:

- **Data Analysis in Biology** at UZH. This is a 14 week course in the spring semester with 3-400 students. We love teaching this course! You can see the content here: [BIO144 Course Book](https://opetchey.github.io/BIO144_Course_Book/){target="_blank"}.
- **Biodiversity Assessment and Monitoring Field Course** taught at Elm in Glarus Sud, with Florian Altermatt and others. This is a 5 day field course in the summer semester with 20-30 students. Students are introduced to alpine biodiversity, and then do a small self-directed research project. We love teaching this course also!

Owen is also one of the founders and members of [R4All](https://r4all.org/){target="_blank"}, a group that teaches R to all-comers. R4All has produced two books:

- [Getting Started with R: An Introduction for Biologists](https://global.oup.com/academic/product/getting-started-with-r-9780198787846){target="_blank"}
- [Insights from Data with R: An Introduction for the Life and Environmental Sciences](https://global.oup.com/academic/product/insights-from-data-with-r-9780198849827){target="_blank"}

